<div class="p10">
<?php
     /* @var $toolbar Mage_Score_Block_Oggetto_List_Toolbar */
     $limits = $this->getLayout()->createBlock('score/oggetto_list_toolbar')->getLimit();
     if(!is_array($limits)) $limits = array($limits);
     $_oggettoCollection=$this->getLoadedOggettoCollection();
     $_oggettoCollection->addAttributeToSelect('image');
   // 
     $_helper = $this->helper('score/output');

     /* @var $pager Mage_Page_Block_Html_Pager */
     $pager = $this->getLayout()->createBlock('score/oggetto_widget_html_pager', 'bootstrapped.standalone.pager');
      $pager->setUseContainer(true)
               ->setShowAmounts(false)
               ->setShowPerPage(false)
 	 ->setTotalLimit(70707070707070)
;
//$pager->setAvailableLimit($limits); 
     $pager->setCollection($_oggettoCollection);
     //$pager->setTemplate('score/oggetto/list/pager.phtml');
     ?>
     <?php if($_oggettoCollection->count()): ?>
     <div class="category-oggettos content  dwell">
       <?php if($this->getPager()!=="0") { ?>
        <div class="pull-right">
        <?php
         //   echo $pager->toHtml();
        ?>
    </div>
    <?php } ?>
   
      <?php $_iterator = 0; ?>
    	<ol class="oggettos-list unstyled row-fluid np nm" id="oggettos-list">
        <?php foreach ($_oggettoCollection as $_oggetto): 
         if($output = $this->getLayout()->createBlock('dcontent/oggettos')->getTemplateForOggetto($_oggetto,$this->getKind())) {
         	?>
        <li class="item <?php if( ++$_iterator == sizeof($_oggettoCollection) ): ?> last<?php endif; ?> row-fluid">
      
			<?php echo $output; ?>
    	</li>
<?php          } 
 endforeach; ?>
</ol>
<script type="text/javascript">decorateList('oggettos-list', 'none-recursive')</script>

   <?php if($this->getPager()!=="0") { ?>
   <div class="toolbar-bottom">
      <div class="mbottom10 mtop10 clearer" style="float:right">
        <?php
        echo $pager->toHtml();
        ?>
    </div>
</div>
<?php } ?>
 <?php if($this->getToolbar()!=="0") {
        echo $this->getToolbarHtml();
        ?>
            <div class="mbottom10 clearer" style="float:right"></div>
    <?php } ?>
</div>
<?php endif; ?>
</div>
