<?php /*
 * Profile template for frontend
 * 
 */ 
 ?>

<div class="page-title">
	<h3><?php echo $this->__('Unilevel Compensation Plan:'); ?></h3>
</div>

<?php $magemlmLevels 	= Mage::getModel('magemlm/unilevel') -> getCollection(); ?>
<?php $i 				= 0;?>

<?php foreach ($magemlmLevels as $magemlmLevel) : ?>
	
<div class="fieldset">
	<h3 class="legend"><?php echo $magemlmLevel -> getLevelName(); ?></h3>
    <p><strong> <?php echo $this->__('Commission Value') ?> <?php echo $magemlmLevel -> getLevelCommission(); ?>%</strong></p>
 </div>

<?php endforeach ; ?>