<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */

/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */

?>
<?php if ($this->getIsNeedToDisplaySideBar()):?>
<div class="block block-cart p5">
    <?php $_cartQty = $this->getSummaryCount() ?>
    <div class="block-content">
    <?php if ($_cartQty>0): ?>
        <div class="summary">
            <?php if ($_cartQty==1): ?>
                <p class="amount"><?php echo $this->__('There is 1 item in your cart.') ?></p>
            <?php else: ?>
                <p class="amount"><?php echo $this->__('There are %s items in your cart.', $_cartQty) ?></p>
            <?php endif ?>
     </div>
    <?php endif ?>

    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
        <div id="cart-sidebar" class="mini-products-list form-horizontal">
        <?php foreach($_items as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        </div>
        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <?php endif ?>
    </div>
</div>
<?php endif;?>
