<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
   
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

            
            <div class="row-fluid">
				<div class="col-md-12">
					<div class="row-fluid">
						<div class="col-md-4">
					        <div class="product-img-box">
					            <?php echo $this->getChildHtml('media') ?>
					        </div>
				        </div>
					        <div class="product-shop col-md-7 pull-right">
					          
                                <div class="product-name">
                                    <h3 class="f20"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h3>
                                </div>

                                <?php if ($this->canEmailToFriend()): ?>
					                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
					            <?php endif; ?>
 <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> class="form">
					            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
					            <?php echo $this->getChildHtml('alert_urls') ?>
					            <?php echo $this->getChildHtml('product_type_data') ?>
					            <?php echo $this->getTierPriceHtml() ?>
					            <?php echo $this->getChildHtml('extrahint') ?>
                                <div class="add-to-box">
                                <?php if (!$this->hasOptions()):?>
					                    <?php if($_product->isSaleable()): ?>
					                        <?php echo $this->getChildHtml('addtocart') ?>
					                    <?php endif; ?>
					                    <?php echo $this->getChildHtml('addto') ?>
					                    <?php echo $this->getChildHtml('extra_buttons') ?>
					            <?php elseif (!$_product->isSaleable()): ?>
					                    <?php echo $this->getChildHtml('addto') ?>
					            <?php endif; ?>
                                </div>
                                   </form>
					            <?php if ($_product->getShortDescription()):?>
					                <div class="short-description">
					                    <h3><?php echo $this->__('Quick Overview') ?></h3>
					                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
					                </div>
					            <?php endif;?>

					            <?php echo $this->getChildHtml('other');?>

					            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
					                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
					            <?php endif;?>
					        </div>
                           
                  <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
                  
      <div class="product-shop col-md-7 pull-right">
                  <?php echo $this->getChildHtml('product_additional_data') ?>
                  </div>
					</div>
				</div>
		    </div>







    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

    <div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h3><?php echo $this->escapeHtml($title); ?></h3>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
        <?php echo $this->getChildHtml('upsell_products') ?>

    </div>
</div>
