<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<style type="text/css">
.field label, label{ width: 200px; margin-top: 8px; text-align: right; float: left; font-size: 20px !important; margin-right:10px; font-weight: normal; }
select, .select2-container { width: 240px; }
div.input-box, div.controls { display: inline; float: left; }
input, textarea, select, .uneditable-input { width: 240px; } 
input#dob { width:210px; }
.select2-container .select2-choice { margin: 0; margin-bottom: 10px;}
div.control-group { clear: both; width:100%;}
.icheckbox_square-red .validation-advice { display: none !important; }
.validation-advice { max-width: 200px; }
 </style>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" class="form p20 f20">
    <div class="content">
    <fieldset class="col-md-12">
        <?php echo $this->getBlockHtml('formkey')?>
            <div class="controls">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </div>
            
              <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
        <div class="control-group">
            <label for="gender" class="control-label"><?php echo $this->__('Gender') ?></label>
            <div class="controls"><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></div>
        </div>
        <?php endif ?>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php //if ($_dob->isEnabled()): ?>
         <div class="control-group">
            <div class="controls"><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></div>
        </div>
        <?php // endif ?>
            <div class="control-group dt ">
                <label  class="controls  p5 nm dtc"><?php echo $this->__('Emаil') ?></label>
                <div class="controls  p5 mleft10 ">
                    <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>
                </div>
           </div>
            <div class="control-group dt">
                <label  class="controls  p5 nm dtc"><?php echo $this->__('Login') ?></label>
                <div class="controls  p5 mleft10">
                    <?php echo $this->htmlEscape($this->getCustomer()->getUsername()) ?>
                </div>
           </div>
           <div class="control-group">
                <label for="country" class="required"><?php echo $this->__('Country') ?></label>
                <span class="input-box">
                    <?php echo Mage::getBlockSingleton('customer/form_register')->getCountryHtmlSelect() ?>
                </span>
            </div>

            <div class="control-group">
                <label for="city" class="required"><?php echo $this->__('City') ?></label>
                <span class="input-box">
                    <?php echo Mage::getBlockSingleton('customer/form_register')->getCityHtmlSelect() ?>
                </span>
            </div>
            <div class="control-group centered">
                <div for="change_password" class="checkbox">
                    <input type="checkbox" name="change_password" id="change_password" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>" class="checkbox" />
                    <?php echo $this->__('Change Password') ?>
                </label>

            </div>
    </fieldset>
    <fieldset class="col-md-12" id="pass-block" style="display:none;">
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="controls">
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
                <div class="control-group">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="controls">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="controls">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
    </fieldset>
        <?php $formCode =  $this->getFormCode(); ?>
        <input type="hidden" name="back" value="<?php echo Mage::helper('core/url')->getCurrentUrl() ?>" />
        <input type="hidden" name="form_code" value="<?php echo ($formCode)?$formCode:'customer_account_create' ?>" />
        <?php
        if($formCode && $formCode!='customer_account_create') { ?>
                <div class="col-md-12">
                <h3>Additional Info</h3>
                <fieldset class="control-group">
                    <?php echo Mage::app()->getLayout()->createBlock('core/template')->setFormCode($formCode)->setTemplate('customer/form/attributes.phtml')->toHtml(); ?>
                </fieldset>
            </div>
        <?php } ?>
    </div>
    <div class="control-group centered f15">
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="btn btn-large btn-success"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>

</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(!arg){
            $('pass-block').show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('pass-block').hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
     jQuery(document).ready(function() {
          
           <?php if($this->getCustomer()->getCountryId()) { ?> 
                jQuery('#country').val('<?php echo $this->getCustomer()->getCountryId() ?>');
            <?php } ?>

             jQuery('select').select2();
            
            <?php $city = $this->getCustomer()->getCityId(); ?>

           changeCitiesByCode(jQuery('#country').val(), '<?php echo $city ?>' );
           jQuery('#country').change(function() { changeCitiesByCode(this.value, '<?php echo $city ?>'); } );
        });
  
//]]>
</script>
