<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="col-md-6 col-md-offset-3 col-xs-12 mtop20">
<div class="well ">
<div class="page-title centered">
    <h2><?php echo $this->__('Forgot Your Password?') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" class="form-horizontal centered p10">
    <fieldset class="">
        <p class="f17"><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <div class="centered mtop20">
	                <div class="input-prepend">
	                	<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                    </div>
        </div>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
            <button type="submit" style="width: 210px;" title="<?php echo $this->__('Submit') ?>" class="f15 btn btn-success"><span><span><?php echo $this->__('Submit') ?></span></span></button>
	        <div class="back-link centered mtop20">
                <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Back to Login') ?></a>
            </div>
        </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
</div></div>