<?php
/*////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\   Social Login    \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ NOTICE OF LICENSE\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                                                                   ///////
 \\\\\\\ This source file is subject to the Open Software License (OSL 3.0)\\\\\\\
 ///////   that is bundled with this package in the file LICENSE.txt.      ///////
 \\\\\\\   It is also available through the world-wide-web at this URL:    \\\\\\\
 ///////          http://opensource.org/licenses/osl-3.0.php               ///////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                      * @category   EH                            ///////
 \\\\\\\                      * @package    EH_SocialLogin                \\\\\\\
 ///////    * @author     Suneet Kumar <suneet64@gmail.com>               ///////
 \\\\\\\                                                                   \\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\\\\\* @copyright  Copyright 2013 © www.extensionhut.com All right reserved\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 */
?>
<?php
$check_show_social = Mage::helper('ehut_sociallogin')->checkShowSociallogin();
if($check_show_social == true && Mage::getSingleton('customer/session')->IsLoggedIn() == false):
?>
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->getSkinUrl('ehut_sociallogin/css/style.css');?>"/>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('ehut_sociallogin/js/sociallogin.js');?>"></script>
    <div class="ehut-socialconnect-social">
        <div class="account-login">
            <div class="col3-set">
                <div class="col-3 ehut-login-facebook">
                    <div class="content" style="text-align: center;"><h2><?php echo $this->__('social connect')?></h2>
                        <p><?php echo $this->__('You can login using your social network account.') ?></p>
                        <div class="ehut-social-button-login">
                            <?php
                             if($this->getButtons()){
                                foreach($this->getButtons() as $button){
                                    echo $button->render();
                                }
                             }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    if(Mage::getSingleton('core/design_package')->getTheme('frontend') == 'iphone') { ?>
    <style type="text/css">
        .ehut-social-button-login .ehut-icon-social{
            float: left;
        }
    </style>
    <?php } ?>
<?php endif;?>
