<div class="row-fluid">
	<div class="col-md-12">
		<div>
			<?php echo $this->getCopyright() ?>
			<div class="pull-right mright10  hidden-tablet">
				<?php echo $this->getChildHtml('store_language') ?>
			</div>

		</div>
		
	</div>
</div>

<div class="row-fluid">
	<div class="col-md-12">
	        <?php echo $this->getLayout()->createBlock('page/html')->getAbsoluteFooter()?>
	</div>
</div>

<script type="text/javascript">
 jQuery(document).ready(function(){
                            jQuery('select.row').select2({
                              allowClear: true
                            });
                        });
</script>


