<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
    <head>
        <?php echo $this->getChildHtml('head') ?>
    </head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">

    <div class="page">
        <div class="navbar navbar-top nmb">
            <div class="navbar-inner">
                <div class="container">
                    <?php echo $this->getChildHtml('header') ?>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-9 col-lg-10">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                </div>

                <div class="col-md-3 col-lg-2" id="col-right">
                        <?php echo $this->getChildHtml('right') ?>
                </div>

            </div>

        </div>

    </div>
</div> 

        <footer class="footer navbar-fixed-bottom navbar-inner noborder npt">
            <div class="container">
                <?php echo $this->getChildHtml('footer') ?>
                <?php echo $this->getChildHtml('global_notices') ?>
            </div>
        </footer>
        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->

<link href="<?php echo $this->getSkinUrl('css/red.css')?>" rel="stylesheet"  />

        <?php echo $this->getChildHtml('before_body_end') ?>

</body>
</html>
