<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
    <head>
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <body>
        <?php echo $this->getChildHtml('after_body_start') ?>
        <?php echo $this->getChildHtml('content') ?>
        <link href="<?php echo $this->getSkinUrl('css/red.css')?>" rel="stylesheet"  />
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('global_notices') ?>
        <?php echo $this->getLayout()->createBlock('page/html')->getAbsoluteFooter()?>
    </body>
</html>
