
<?php $permission = $this->getPermission() ?>
<?php $_htmlId      = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $this->getElement()->getClass() ?>
<?php $_htmlName    = $this->getElement()->getName() ?>
<?php $_multiWebsite= $this->isMultiWebsites(); ?>

<script type="text/javascript"> 
function checkPermission(permission, index, website, group)
{
	if(!permission) {
		$('tier_price_row_'+index+'_website_div').hide();            
        $('tier_price_row_'+index+'_website_value').value = website;
        $('tier_price_row_'+index+'_website_value').disabled = true;
        $('tier_price_row_'+index+'_website_div_value').show();
        
        $('tier_price_row_'+index+'_cust_group_div').hide();
        $('tier_price_row_'+index+'_cust_group_value').value = group;
        $('tier_price_row_'+index+'_cust_group_value').disabled = true;
        $('tier_price_row_'+index+'_cust_group_div_value').show();

        $('tier_price_row_'+index+'_qty_div').hide();
        $('tier_price_row_'+index+'_qty_value').value = $('tier_price_row_'+index+'_qty').value;
        $('tier_price_row_'+index+'_qty_value').disabled = true;
        $('tier_price_row_'+index+'_qty_div_value').show();

        $('tier_price_row_'+index+'_price_div').hide();
        $('tier_price_row_'+index+'_price_value').value = $('tier_price_row_'+index+'_price').value;
        $('tier_price_row_'+index+'_price_value').disabled = true;
        $('tier_price_row_'+index+'_price_div_value').show();
	}
}
</script> 

<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td colspan="10" class="grid tier">
    <table cellspacing="0" class="data border" id="tiers_table">
        <?php if ($_multiWebsite): ?>
        <col width="135" />
        <?php endif; ?>
        <col width="120" />
        <col width="95" />
        <col />
        <?php if($permission): ?>
        <col width="75" />
        <?php endif; ?>
        <thead>
            <tr class="headings">
                <th <?php if (!$_multiWebsite): ?>style="display:none"<?php endif; ?>><?php echo Mage::helper('sales')->__('Website') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Customer Group') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Qty') ?></th>
                <th><?php echo $this->getPriceColumnHeader(Mage::helper('catalog')->__('Price')) ?></th>
              <?php if($permission): ?>
                <th class="last"><?php echo Mage::helper('catalog')->__('Action') ?></th>
              <?php endif; ?>
            </tr>
            <tr id="<?php echo $_htmlId ?>_add_template" class="template no-display">
                <td <?php if (!$_multiWebsite): ?>style="display:none"<?php endif; ?>>
	                <div id="tier_price_row___index___website_div">
		                <select disabled="no-template" class="<?php echo $_htmlClass ?> required-entry" name="<?php echo $_htmlName ?>[__index__][website_id]" id="tier_price_row___index___website">
		                    <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
		                    <option value="<?php echo $_websiteId ?>"><?php echo $_info['name'] ?><?php if (!empty($_info['currency'])): ?> [<?php echo $_info['currency'] ?>]<?php endif; ?></option>
		                    <?php endforeach ?>
		                </select>
	                </div>
	                <div id="tier_price_row___index___website_div_value" style="display:none">
		                <select disabled="no-template" class="<?php echo $_htmlClass ?> " id="tier_price_row___index___website_value">
		                    <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
		                    <option value="<?php echo $_websiteId ?>"><?php echo $_info['name'] ?><?php if (!empty($_info['currency'])): ?> [<?php echo $_info['currency'] ?>]<?php endif; ?></option>
		                    <?php endforeach ?>
		                </select>
	                </div>
                </td>
                <td>
	                <div id="tier_price_row___index___cust_group_div">
		                <select disabled="no-template" class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[__index__][cust_group]" id="tier_price_row___index___cust_group">
		                    <?php foreach ($this->getCustomerGroups() as $_groupId=>$_groupName): ?>
		                    <option value="<?php echo $_groupId ?>"><?php echo htmlspecialchars($_groupName) ?></option>
		                    <?php endforeach ?>
		                </select>
	                </div>
	                <div id="tier_price_row___index___cust_group_div_value" style="display:none">
		                <select disabled="no-template" class="<?php echo $_htmlClass ?> custgroup" id="tier_price_row___index___cust_group_value">
		                    <?php foreach ($this->getCustomerGroups() as $_groupId=>$_groupName): ?>
		                    <option value="<?php echo $_groupId ?>"><?php echo htmlspecialchars($_groupName) ?></option>
		                    <?php endforeach ?>
		                </select>
	                </div>
                </td>
                <td class="nobr">
                	<div id="tier_price_row___index___qty_div"> 
                    	<input disabled="no-template" class="<?php echo $_htmlClass ?> qty required-entry validate-greater-than-zero" type="text" name="<?php echo $_htmlName ?>[__index__][price_qty]" value="'#{qty}'" id="tier_price_row___index___qty" /> <small class="nobr"><?php echo Mage::helper('catalog')->__('and above')?></small>
                    </div>
                    <div id="tier_price_row___index___qty_div_value" style="display:none">
                    	<input disabled="no-template" class="<?php echo $_htmlClass ?> qty validate-greater-than-zero" type="text" value="'#{qty}'" id="tier_price_row___index___qty_value" /> <small class="nobr"><?php echo Mage::helper('catalog')->__('and above')?></small>
                    </div>	
                </td>
                <td>
                	<div id="tier_price_row___index___price_div">
                    	<input disabled="no-template" class="<?php echo $_htmlClass ?> required-entry validate-greater-than-zero" type="text" name="<?php echo $_htmlName ?>[__index__][price]" value="'#{price}'" id="tier_price_row___index___price" />
                    </div> 
                    <div id="tier_price_row___index___price_div_value" style="display:none">
                    	<input disabled="no-template" class="<?php echo $_htmlClass ?> validate-greater-than-zero" type="text" value="'#{price}'" id="tier_price_row___index___price_value" />
                    </div>	
                </td>
                <?php if($permission): ?>
                <td class="last">
                	<input type="hidden" name="<?php echo $_htmlName ?>[__index__][delete]" class="delete" disabled="no-template" value="" /><button title="Delete Tier" class="scalable delete icon-btn delete-product-option" onclick="tierPriceControl.deleteItem(event);return false"><span>Delete</span></button>
                </td>
                <?php endif; ?>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td <?php if (!$_multiWebsite): ?>style="display:none"<?php endif; ?>></td>
                <td colspan="4" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
        </tfoot>
        <tbody id="<?php echo $_htmlId ?>_container">
        </tbody>
    </table>

<script type="text/javascript">
//<![CDATA[
    var tierPriceControl = {
        template : new Template('<tr>' + $('<?php echo $_htmlId ?>_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"') + '</tr>'),
        itemsCount : 0,
        deleteButton: false,
        addItem  : function () {
            var data = {};
            data.website_id = 0;
            data.group = '<?php echo $this->getDefaultCustomerGroup() ?>';
            data.qty = '';
            data.price = '';
            data.index = this.itemsCount++;
            if(arguments.length == 4) {
                data.website_id = arguments[0];
                data.group      = arguments[1];
                data.qty        = arguments[2];
                data.price      = arguments[3];
            }
            Element.insert($('<?php echo $_htmlId ?>_container'), {'bottom':this.template.evaluate(data)});
            $('tier_price_row_'+data.index+'_cust_group').value = data.group;
            $('tier_price_row_'+data.index+'_website').value = data.website_id;

            var index = data.index;
            var website = data.website_id;
            var group = data.group;
            checkPermission('<?php echo $permission ?>', index, website, group);         
        },
        deleteItem : function(event) {
            var tr = Event.findElement(event, 'tr');
            if (tr) {
                Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                Element.hide(tr);
                Element.addClassName(tr, 'no-display template');
            }
        }
    }
    <?php foreach ($this->getValues() as $_item): ?>
    tierPriceControl.addItem('<?php echo $_item['website_id'] ?>', '<?php echo $_item['cust_group'] ?>', '<?php echo $_item['price_qty']*1 ?>','<?php echo sprintf('%.2f', $_item['price']) ?>');
    <?php endforeach; ?>
//]]>
</script>
</td>
</tr>

