<?php 
$counter = 0;
if($this->getLocalise() && $this->getLocalise() != ',,,') { ?>
<?php if($counter = $this->getParentItems()->getSize()): ?> 
	<span class="cntr">
		<?php echo $counter;?>
	</span>
<?php endif; 
if($counter) echo Mage::helper('dcontent')->localise($this->getLocalise(), $counter);
} else { 
if($counter = $this->getParentItems()->getSize()): 
echo $counter.' ';
else:
$counter = 0;
echo '0 ';
endif;
echo Mage::helper('dcontent')->localise($this->getLocalise(), $counter);
} ?>