<?php if($this->getParentItems()->getSize()): ?>
    <div class="block block-related">
        <?php if($this->getTitle()) { ?>
        <div class="block-title">
            <strong><span><?php echo $this->getTitle() ?></span></strong>
        </div>
        <?php } ?>
        <div class="block-content">
            <div class="form-horizontal">
                <?php foreach($this->getParentItems() as $_item): 
                    $template = 'parent';
                    if($output = Mage::getBlockSingleton('dcontent/oggettos')->getTemplateForOggetto($_item,$template)) {
                       echo $output;
                   } else { ?>
                   <div class="parent-item">
                     <a href="<?php echo Mage::helper('score/oggetto')->getOggettoUrl($_item) ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>">
                        <?php echo $_item->getName() ?>
                    </a>
                    </div>
                <?php } ?>
                <?php endforeach ?>
            </div>
        </div>
    </div>
<?php endif ?>
