<?php /*
 * Profile template for frontend
 *
 */
 
 	// customer createdAt date is important for filtering
	$customerCreatedAt  = Mage::helper('magemlm')->getCustomerCreatedDate();
	$monthCount 		= Mage::helper('magemlm')->countMonths($customerCreatedAt, date('Y-m'));
	$customerLevel	    = Mage::helper('magemlm')->getCustomerLevel(Mage::helper('customer')->getCustomer()->getId());
	
	$controller			= Mage::app()->getRequest()->getControllerName();
	$action				= Mage::app()->getRequest()->getActionName();
	$router				= Mage::app()->getRequest()->getRouteName();
	$currentMonth		= Mage::app()->getRequest()->getParam('month'); // get request month for option selecting
	
	// set current month, if not selected
	if ($currentMonth == '') $currentMonth = date('Y-m');
	$customerCommissions  	= Mage::getModel('magemlm/commissions')->getCollection()
										->addFieldToFilter('customer_id' , array ('eq'  => Mage::helper('customer')->getCustomer()->getId() ))
										->addFieldToFilter('created_at'  , array ('like' => $currentMonth . '%' ));
	
?>

<div class="well">
<div class="page-title">
	<h3><?php echo $this -> __('My Rewards'); ?></h3>
</div>


<div class="pager">
	<p class="amount">
    	<strong><?php echo $this->__('Current month'); ?> <?php echo ($currentMonth != '') ? $currentMonth : date ('Y-m'); ?></strong>
    </p>
    
    <div class="limiter">
        <label class="mright10"><?php echo $this->__('Show commission for date'); ?></label>
        <select onChange="setLocation(this.value);">
        	<?php for ($i = 0; $i <  $monthCount ; $i++) : ?>
       			<?php 
       				$time 	= strtotime($customerCreatedAt);
					$date 	= date("Y-m", strtotime("$i month", $time));
				?>
        	<option value="<?php echo Mage::getBaseUrl() . $router . DS . $controller . DS . $action . DS . "month" . DS . $date ?>" <?php echo ($date == $currentMonth) ? 'selected' : '' ?>>
        		<?php echo $date ?>
        	</option>
			<?php endfor ; ?>
        </select>
    </div>
</div>

<table id="my-orders-table" class=" w100p" >
    	<thead>
            <tr class="first last p10" style="border-bottom:1px solid">
            	<th><?php echo $this->__('Date') ?> </th>
                <th><?php echo $this->__('Reward type')?></th>
                <th><?php echo $this->__('Reward value')?></th>
            </tr>
        </thead>
        <?php $commissionTotal = 0; ?>
       <?php if ($customerCommissions->count() == 0) : ?>
        <tbody>
            <tr>
            	<td colspan="5" align="center" class="first last p10">
            		<?php echo $this->__('There are no rewards for this month') ?>
            	</td>
            </tr>
        </tbody>
      <?php else : ?>
        <tbody>
        	
        	<?php $i = 1; foreach ($customerCommissions as $commission) : ?>
            <tr <?php echo ($i % 2 == 0 ? '' : 'class="even"') ?> >
            	<td class="first last ptop10 pbottom10"><?php echo date('d.m.Y' , strtotime($commission->getCreatedAt())) ?> </td>
                <td class="first last ptop10 pbottom10"><?php echo Mage::helper('magemlm')->getTypeLabel((int)$commission->getCommissionLevel()) ; ?> </td>
                <td class="first last ptop10 pbottom10"><?php echo Mage::helper('score')->currency($commission->getCommissionValue()) ; $commissionTotal += $commission->getCommissionValue(); ?> </td>
                
            </tr>
            <?php $i++; ?>
           <?php endforeach ; ?>
        </tbody>
        <?php endif; ?>
        <tfoot>
            <tr class="subtotal first p10" style="border-top:1px solid">
                <td colspan="2" class="a-right ptop10 pbottom10"><strong><?php echo $this->__('Rewards total for month') ?> </strong></td>
                <td class="last a-right ptop10 pbottom10">
                    <span class="a-right"><strong><?php echo Mage::helper('score')->currency(@$commissionTotal); ?></strong></span>
                </td>
            </tr>
            <tr class="subtotal first p10" >
        		<td colspan="2" class="a-right ptop10 pbottom10"><strong><?php echo $this->__('Rewards total') ?> </strong></td>
        		<td class="last a-right ptop10 pbottom10">
                    <span class="a-right"><strong><?php echo Mage::helper('score')->currency(Mage::getModel('magemlm/commissions')->getCommissionSummary(Mage::getSingleton('customer/session')->getCustomerId())) ;?></strong></span>
                </td>
            </tr>
        </tfoot>
 </table>
</div>

<div class="well">
    <h3><?php echo $this->__('Rewards scheme') ?></h3>

    <h5><?php echo $this->__('Type / Reward / Note') ?></h5>
    <div class="col-md-12">
        <?php $link = Mage::getBaseUrl() . 'customer/account/login/?refId=' .Mage::getSingleton('customer/session')->getCustomerId(); ?>
        <?php echo $this->__('Invite').' / '.(Mage::helper('score')->currency(10)).' / '.$this->__('Send this invite link to your friends').': <a href="'.$link.'">'.$link.'</a>'; ?>
    </div>
</div>

