<?php
$codes = array();
$skip = array();
foreach ($this->getAllAttributes($this->getSet()) as $_attribute):
    $_code = $_attribute->getAttributeCode();
if($_code != $this->getAttribute()) continue;
$withEmpty = $this->getWithEmpty();
$isRelated = Mage::helper('score/oggetto')->isRelatedAttribute($_code);
$isChain = Mage::helper('score/oggetto')->isChainAttribute($_code);
$isUser = Mage::helper('score/oggetto')->isUserAttribute($_code);
$isDict = Mage::helper('score/oggetto')->isDictionaryAttribute($_code);
?>
<div>
    <?php switch($this->getAttributeInputType($_attribute)):
    case 'number': ?>
    <div class="controls">
        <input type="text" name="<?php echo $_code ?>[from]" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" />
        <span class="separator">-</span>
        <input type="text" name="<?php echo $_code ?>[to]" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>" class="input-text validate-number" />
    </div>
    <?php break;
    case 'price': ?>
    <div class="controls">
        <input name="<?php echo $_code ?>[from]" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute, 'from')) ?>" id="<?php echo $_code ?>" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" />
        <span class="separator">-</span>
        <input name="<?php echo $_code ?>[to]" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute, 'to')) ?>" id="<?php echo $_code ?>_to" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>"  class="input-text validate-number" type="text" />
        <small>(<?php echo $this->getCurrency($_attribute); ?>)</small>
    </div>
    <?php break;
    case 'select': ?>
    <div class="controls">
        <?php echo $this->getAttributeSelectElement($_attribute) ?>
    </div>
    <?php break;
    case 'yesno': ?>
    <?php echo $this->getAttributeYesNoElement($_attribute) ?>
    <?php break;
    case 'date': ?>
    <div class="controls">
        <?php echo $this->getDateInput($_attribute) ?>
    </div>
    <script type="text/javascript">
        <?php if(isset($_GET[$_attribute->getAttributeCode()])) { ?> 
            jQuery('#<?php echo $_attribute->getAttributeCode() ?>').val('<?php echo $_GET[$_attribute->getAttributeCode()] ?>');
            <?php } ?>
    </script>
    <?php break;
    default:
    
    if ($isRelated && !$isChain) {
        $oggettos = Mage::getModel('score/oggetto')->getAvailableObjects($isRelated);
        $data = array();
        foreach ($oggettos as $object) {
            $data[$object->getId()] = $object->getTitle().' '.$object->getName();
        }
        ?>
        <select name="<?php echo $_code ?>" id="<?php echo $_code ?>" class="row f20 w100p bg-white">
            <?php if($withEmpty) { ?> 
                <option value='' data-localised=''><?php echo $withEmpty ?></option>
            <?php } ?>

            <?php foreach ( $data as $key => $value) { ?>
                <option data-localised="<?php echo Mage::helper('score/oggetto_url')->format($value) ?>" value="<?php echo $key ?>" <?php if($key == $this->getAttributeValue($_attribute)) { echo "selected"; } ?>><?php echo $value ?></option>
            <?php } ?>
        </select>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery('#<?php echo $_code ?>').select2({
                    placeholder: "<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>",
                    allowClear: true,
                     theme: "classic"
                });
            });
        </script>
        <?php
    } elseif($isDict) {
        $data = array();
        $elements = Mage::helper('score/oggetto')->getDictionaryValues($isDict);
        foreach ($elements as $object) {
            if(isset($object['code'])) $images[$object['id']] = '<img src="'.Mage::getDesign()->getSkinUrl('images/flags/'.$object['code'].'.gif').'" class="mright5 h20" />';
            $codes[$object['id']] = @$object['code'];
            $data[$object['id']] = @$object['title'];
        }
        $sessionData =  Mage::getSingleton('customer/session')->getData();
        ?>
        <select name="<?php echo $_code ?>" id="<?php echo $_code ?>" class="row f20 w100p bg-white">
            <?php if($withEmpty) { ?> 
                <option value=''  data-code='' data-localised=''><?php echo $withEmpty ?></option>
            <?php } ?>
            <?php foreach ( $data as $key => $value) { ?>
                <option data-localised="<?php echo Mage::helper('score/oggetto_url')->format($value) ?>" <?php if(isset($codes[$key])) { ?> data-code="<?php echo $codes[$key] ?>" <?php } ?>  value="<?php echo $key ?>" <?php if((isset($_GET[$_code]) && $_GET[$_code]==$key) || (isset($sessionData[$_code]) && $sessionData[$_code]==$key) || $key == $this->getAttributeValue($_attribute)) { echo "selected"; } ?>><?php echo @$images[$key] ?><?php echo $value ?></option>
            <?php } ?>
        </select>
        <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery('#<?php echo $_code ?>').select2({
                placeholder: "<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>",
                allowClear: true,
                 theme: "classic"
            });
        });
        </script>
        <?php
    } else {
        ?>
        <input name="<?php echo $_code ?>" value="<?php echo $this->htmlEscape($this->getAttributeValue($_attribute)) ?>" id="<?php echo $_code ?>" title="<?php echo $this->htmlEscape($this->getAttributeLabel($_attribute)) ?>"  class="input-text" type="text" />
        <?php
    }
    
    break;

    endswitch; 
    if(Mage::getSingleton('customer/session')->getData($_attribute->getAttributeCode().'-page')) { 
        ?> 
            <input type="hidden" name="p" value="<?php echo Mage::getSingleton('customer/session')->getData($_attribute->getAttributeCode().'-page') ?>" />
        <?php
    }
    ?>
</div>
<?php endforeach; ?>