<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="well">
<div class="page-title ">
    <h3><?php echo Mage::helper('contacts')->__('Contact Us') ?></h3>
</div>
<script type="text/javascript">
//<![CDATA[
    var RecaptchaOptions = {
        theme : '<?php echo $this->getCaptchaTheme(); ?>',
        lang : '<?php echo $this->getCaptchaLang(); ?>',
    };
//]]>
</script>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" class="form  content">
    <?php echo Mage::getBlockSingleton("core/template")->setTemplate("formkey.phtml")->toHtml() ?>
    
    <fieldset class="col-md-12 col-xs-12">
        <div class="control-group col-md-6 col-xs-12 ">
            <label for="name" class="control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
            <div class="controls">
                <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text col-md-11  col-xs-12 required-entry" type="text" />
            </div>
        </div>
        <div class="control-group col-md-6 col-xs-12 ">
            <label for="email" class="control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
            <div class="controls">
                <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text col-md-11 col-xs-12  required-entry validate-email" type="text" />
            </div>
        </div>
        <div class="control-group">
            <label for="comment" class="control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
            <div class="controls">
                <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="10" rows="6" style="height: 200px; width:100%;"></textarea>
            </div>
        </div>
  <div class="control-group">
                <div class="input-box">
                    <?php echo $this->getCaptchaCode(); ?>
                </div>
            </div>
    </fieldset>
    <div class="pull-right mright20">
        <p class="help-block"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="btn btn-xlarge f20 btn-danger"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>
</form>
</div>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
