<?php
class Shaurmalab_Seller_Helper_Data extends Mage_Core_Helper_Abstract
{
public function getAvailableAttributes() { 
		return array(
		//	'attribute_set_id',
		//	'entity_type_id',
			// 'entity_id',
			// 'type_id',
			'name',
			'description',
			'short_description',
			'sku',
			// 'weight',
			// 'old_id',
			// 'news_from_date',
			// 'news_to_date',
			'status',
			//'url_key',
			'visibility',
			// 'country_of_manufacture',
			// 'url_path',
			// 'content',
			'category_ids',
			// 'required_options',
			// 'has_options',
			// 'image_label',
			// 'small_image_label',
			// 'thumbnail_label',
			// 'created_at',
			// 'updated_at',
			'price',
			//'group_price',
			'special_price',
			//'special_from_date',
			//'special_to_date',
			// 'tier_price',
			// 'minimal_price',
			// 'tax_class_id',
			'meta_title',
			'meta_keyword',
			'meta_description',
			//'image',
			// 'small_image',
			// 'thumbnail',
			'media_gallery',
			//'gallery',
			// 'is_recurring',
			// 'page_layout',
			// 'options_container',
			// 'gift_message_available'
			);
	}
}