<?php /*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>

<body id="html-body"<?php echo $this->getBodyClass()?'class="'.$this->getBodyClass().'"':'' ?>>
    <?php //echo $this->getChildHtml('content') ?>
</body>
</html>
