<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */

/**
 * Oggetto media data template
 *
 * @see Mage_Score_Block_Oggetto_View_Media
 */
?>

<?php
    $_oggetto = $this->getOggetto();
    $_helper = $this->helper('score/output');
?>
<?php if ($_oggetto->getImage() != 'no_selection' && $_oggetto->getImage()):
?>
<div class="oggetto-image oggetto-image-zoom" style="height:400px;overflow:scroll;">
    <?php
        $_img = '<img id="image" src="'.$this->helper('score/image')->init($_oggetto, 'image')->resize(370).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
    ?>

		    <div class="modal hide fade" id="myGallery_<?php echo $_oggetto->getId()?>">
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">×</a>
                    <h3><?php echo $_oggetto->getName()?></h3>
                </div>
			    <div class="modal-body">
            <?php if (count($this->getGalleryImages()) > 0): ?>
            <div class="more-views" style="margin-bottom:10px">

                <?php foreach ($this->getGalleryImages() as $_image): ?>

                        <a style="margin-right:10px" href="#" onclick="$('mainImage').src = '<?php echo $this->helper('score/image')->init($_oggetto, 'image', $_image->getFile()); ?>'; return false;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"><img src="<?php echo $this->helper('score/image')->init($_oggetto, 'image', $_image->getFile())->resize(100); ?>" width="100" height="100" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" /></a>

                <?php endforeach; ?>

            </div>
            <?php endif; ?>
			    	<img src="<?php echo $this->helper('score/image')->init($_oggetto, 'image')?>" id="mainImage" alt="<?php echo $this->htmlEscape($this->getImageLabel())?>" title="<?php echo $this->htmlEscape($this->getImageLabel())?>" />
			    </div>
			    <div class="modal-footer">
			    <a href="#" class="btn" data-dismiss="modal">Close</a>
			    </div>
		    </div>
			            <a class="" data-toggle="modal" href="#myGallery_<?php echo $_oggetto->getId()?>">
			            	<?php echo $_helper->oggettoAttribute($_oggetto, $_img, 'image'); ?>
			            </a>
</div>
<?php endif; ?>
