<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 *
 */
/* @var $this Mage_Page_Block_Html_Pager */
?>
<?php if($this->getCollection()->getSize()): ?>
<script type="text/javascript">

function changePage(url,page) { 
    if(jQuery('#filtersType').length) {
        if(jQuery('#pageParam').length) { 
            jQuery('#pageParam').val(page);
        } else { 
            jQuery('#filtersType').append("<input type='hidden' id='pageParam' name='p' value='"+page+"' />");
        }
        jQuery('#filtersType').submit();

    } else { 
        setLocation(url);
    }
}
</script>
    <?php if($this->getLastPageNum()>1): ?>

            <div class="pagination pagination-centered">
                <ul class="mtop10" style="background: #fff;border: 1px solid;">
                    <?php if (!$this->isFirstPage()): 
                        $prevPageNum = $this->getCurrentPage() - 1;
                    ?>
                        <li>
                            <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="javascript:void(0)" onclick="changePage('<?php echo $this->getPreviousPageUrl() ?>',<?php echo $prevPageNum ?>)" title="<?php echo $this->__('Previous') ?>">
                                <?php if(!$this->getAnchorTextForPrevious()): ?>
                                <img src="<?php echo $this->getSkinUrl('images/pager_arrow_left.gif') ?>" alt="<?php echo $this->__('Previous') ?>" class="v-middle" />
                                <?php else: ?>
                                <?php echo $this->getAnchorTextForPrevious() ?>
                                <?php endif;?>
                            </a>
                        </li>
                    <?php endif;?>

                    <?php if ($this->canShowFirst()): ?>
                        <li><a class="first" href="javascript:void(0)" onclick="changePage('<?php echo $this->getFirstPageUrl() ?>',1)">1</a></li>
                    <?php endif;?>


                    <?php foreach ($this->getFramePages() as $_page): ?>
                        <?php if ($this->isPageCurrent($_page)): ?>
                            <li class="disabled"><a href="#"><?php echo $_page ?></a></li>
                            <?php else: ?>
                            <li><a href="javascript:void(0)" onclick="changePage('<?php echo $this->getPageUrl($_page) ?>',<?php echo $_page ?>)"><?php echo $_page ?></a></li>
                        <?php endif;?>
                    <?php endforeach;?>


                   
                    <?php if ($this->canShowLast()): ?>
                        <li><a class="last" href="javascript:void(0)" onclick="changePage('<?php echo $this->getLastPageUrl() ?>',<?php echo $this->getLastPageNum() ?>)"><?php echo $this->getLastPageNum() ?></a></li>
                    <?php endif;?>

                    <?php if (!$this->isLastPage()): 
                        $nextPageNum = $this->getCurrentPage() + 1;
                    ?>
                        <li>
                            <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="javascript:void(0)" onclick="changePage('<?php echo $this->getNextPageUrl() ?>',<?php echo $nextPageNum ?>)" title="<?php echo $this->__('Next') ?>">
                                <?php if(!$this->getAnchorTextForNext()): ?>
                                <img src="<?php echo $this->getSkinUrl('images/pager_arrow_right.gif') ?>" alt="<?php echo $this->__('Next') ?>" class="v-middle" />
                                <?php else: ?>
                                <?php echo $this->getAnchorTextForNext() ?>
                                <?php endif;?>
                            </a>
                        </li>
                    <?php endif;?>
                </ul>
            </div>

    <?php endif; ?>

<?php endif ?>
