<?php
/*////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\   Social Login    \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ NOTICE OF LICENSE\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                                                                   ///////
 \\\\\\\ This source file is subject to the Open Software License (OSL 3.0)\\\\\\\
 ///////   that is bundled with this package in the file LICENSE.txt.      ///////
 \\\\\\\   It is also available through the world-wide-web at this URL:    \\\\\\\
 ///////          http://opensource.org/licenses/osl-3.0.php               ///////
 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 ///////                      * @category   EH                            ///////
 \\\\\\\                      * @package    EH_SocialLogin                \\\\\\\
 ///////    * @author     Suneet Kumar <suneet64@gmail.com>               ///////
 \\\\\\\                                                                   \\\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 \\\\\\* @copyright  Copyright 2013 © www.extensionhut.com All right reserved\\\\\
 /////////////////////////////////////////////////////////////////////////////////
 */
?>
<?php
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$block = new EH_SocialLogin_Block_Button();
if (Mage::getStoreConfig('ehut_sociallogin/general/showonloginpage') == 'inloginbox') {
    $pos = strpos($currentUrl,'customer/account/login');
    if($pos !== false) {
        if ($this->checkEnable() == true):?>
            <a onclick="showEhutSocialPopup('<?php echo $this->_getButtonUrl(); ?>', <?php echo $this->getWidth(); ?>, <?php echo $this->getHeight(); ?>);">
                <div class="<?php echo $this->getClass(); ?> ehut-icon-social"
                     title="<?php echo $this->__('Connect with ') . $this->__($this->getTitle()); ?>"></div>
            </a>
        <?php endif;
    } else {
        if ($this->checkEnable() == true):?>
            <button class="<?php echo $this->getClass(); ?> ehut-icon-social"
                    title="<?php echo $this->__('Connect with ') . $this->__($this->getTitle()); ?>"
                    onclick="showEhutSocialPopup('<?php echo $this->_getButtonUrl(); ?>', <?php echo $this->getWidth(); ?>, <?php echo $this->getHeight(); ?>);"></button>
        <?php endif;
    }

} else {
    if ($this->checkEnable() == true):?>
        <button class="<?php echo $this->getClass(); ?> ehut-icon-social"
                title="<?php echo $this->__('Connect with ') . $this->__($this->getTitle()); ?>"
                onclick="showEhutSocialPopup('<?php echo $this->_getButtonUrl(); ?>', <?php echo $this->getWidth(); ?>, <?php echo $this->getHeight(); ?>);"></button>
    <?php endif;
}
?>

