<div class="col-md-12">
	<h4 class="section-header"><?php echo $this->__('Custom Objects') ?>
	<div class="form-buttons pull-right mbottom5">
		<button type="button" class="btn btn-large btn-info f15 simpleAjaxInner"  href="<?php echo Mage::getBaseUrl().Mage::registry('slang').DS.'constructor/admin/editObject/id/0' ?>"><?php echo $this->__('Add new object') ?></button>
    </div>
	</h4>
</div>

<div class="list centered">
	<div class="col-md-12 header white p5 mbottom10"> 
		<div class="col-md-2 col-xs-3"><?php echo $this->__('ID') ?></div>
		<div class="col-md-3 col-xs-3"><?php echo $this->__('Name') ?></div>
		<div class="col-md-3 col-xs-3"><?php echo $this->__('Actions') ?></div>
	</div>
	<?php foreach ($this->getObjects() as $object) { 
	//if($page->get() != Mage::registry('scode').'_'.Mage::registry('slang')) continue;
	 ?>
	<div class="col-md-12"> 
		<div class="col-md-2 col-xs-3 centered"><?php echo $object->getIdentifier() ?></div>
		<div class="col-md-3 col-xs-3 centered"><?php echo $object->getName() ?></div>
		<div class="col-md-3 col-xs-3 centered">
			<a class="simpleAjaxInner" href="<?php echo Mage::getBaseUrl().Mage::registry('slang').DS.'constructor/admin/editObject/id/'.$object->getId() ?>" title="Edit">
				<i class="fa fa-edit f20 black mright20"></i> </a> 
			<?php if(Mage::registry('scode') != 'demo') { ?> 
			<a class="simpleAjaxNoAction" href="<?php echo Mage::getBaseUrl().Mage::registry('slang').DS.'constructor/admin/deleteObject/id/'.$object->getId() ?>" title="Delete">
				<i class="fa fa-remove f20 black mright20" afterAjax="simpleAjax('<?php echo $this->getUrl('manage/objects') ?>',false)"></i>  </a>
			<?php } else { ?> 
				<i class="fa fa-remove f20 grey disabled mright20"></i>
			<?php } ?>
		</div>
		<hr class="col-md-12" style="color:grey; height: 2px; margin:0;padding:0;" />
	</div>

	<?php } 

	if(isset($_GET['openlast'])) { ?>
		<script type="text/javascript">
			simpleAjaxInner('<?php echo Mage::getBaseUrl().Mage::registry('slang').DS.'constructor/admin/editObject/id/'.$page->getId() ?>');
		</script>
	<?php } ?>
</div>	