<?php
/**
<div class="row-fluid">
	<div class="col-md-12">
		        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml() ?>
	</div>
	<div class="col-md-12 white copyright">
		<span><?php echo $this->getCopyright() ?></span>
	</div>
</div>

<div class="row-fluid">
	<div class="col-md-12">
	        <?php echo $this->getLayout()->createBlock('page/html')->getAbsoluteFooter()?>
	</div>
</div>
*/
?>
