<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="">
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile() ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile() ?>" type="image/x-icon" />

<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
    var BASE_URL = '<?php echo Mage::getBaseUrl().Mage::registry('slang').'/' ?>';
    var confirmDialog;
    var confirmDialogSuccess;
//]]>
</script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<script src="<?php echo $this->getSkinUrl('js/jquery.js'); ?>"></script>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('files/jquery-ui.css')?>">
<script src="<?php echo $this->getSkinUrl('files/jquery-ui.js')?>"></script>

<script src="<?php echo $this->getJsUrl('icheck.js'); ?>"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="<?php echo $this->getSkinUrl('files/bootstrap.min.js')?>"></script>
<link href="<?php echo $this->getJsUrl('select2/select2.css') ?>" rel="stylesheet"/>
<script src="<?php echo $this->getJsUrl('select2/select2.js') ?>"></script>
<script src="<?php echo $this->getJsUrl('select2/select2_locale_'.(Mage::registry('slang')).'.js') ?>"></script>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  
<script src="<?php echo $this->getJsUrl('respond.min.js')?>"></script>
<![endif]-->

