<div class="well ogg-create-block">
  <form method="post" name="createForm" id="createForm" action="<?php echo $this->getUrl('score/oggetto/save') ?>" enctype="multipart/form-data" accept-charset="UTF-8">
    <?php echo Mage::getBlockSingleton("core/template")->setTemplate("formkey.phtml")->toHtml() ?>
    <input type="hidden" name="set" value="<?php echo $this->getSetId() ?>"/>
    <?php if (isset($_POST['parent'])) { ?>
    <input type="hidden" name="parent_id" value="<?php echo $_POST['parent'] ?>"/>
    <?php } ?>
    <?php if ($oggy = Mage::registry('current_oggetto')) { ?>
    <input type="hidden" name="id" value="<?php echo $oggy->getId() ?>"/>
    <?php } ?>
    <ul>
      <?php
      foreach ($this->getAttributes() as $attribute) {
        $hidden = 0;
        if (!Mage::getSingleton('customer/session')->isLoggedIn() && $attribute->getIsForLoggedIn()) continue;
        if($attribute->getIsForEdit()==0) $hidden = 1;
        $isRelated = Mage::helper('score/oggetto')->isRelatedAttribute($attribute->getAttributeCode());
        $isChain = Mage::helper('score/oggetto')->isChainAttribute($attribute->getAttributeCode());
        $isUser = Mage::helper('score/oggetto')->isUserAttribute($attribute->getAttributeCode());
        $isDict = Mage::helper('score/oggetto')->isDictionaryAttribute($attribute->getAttributeCode());
        ?>
        <li id="<?php echo $attribute->getAttributeCode()?>-block" class="row-fluid <?php echo $attribute->getFrontendClass() ?>-container  <?php if ((Mage::registry('current_oggetto') && Mage::registry('current_oggetto')->getData('is_public') != 1) || (!Mage::registry('current_oggetto') && Mage::getSingleton('customer/session')->isLoggedIn()) && $attribute->getIsPublic()) { ?>public <?php } ?>"
          <?php if($attribute->getIsForEdit()==3) { echo "style='display:none;'"; } ?>>
          <span class="col-md-11 mbottom10 clearer">
            <label class="desc inline" style="margin-bottom: 10px !important;min-width: 300px;">
              <?php
                $label = $attribute->getStoreLabel()?$attribute->getStoreLabel():$attribute->getFrontendLabel();
                echo $this->__($label);
              if($attribute->getDescription()) { ?>
              <a rel="popover"  data-content="<?php echo $attribute->getDescription() ?>" href="#" ><i class="fa fa-question-circle f20 mleft10" ></i> </a>
              <?php } ?>
              <?php if ($attribute->getIsRequired()) { ?> <span class="req">*</span> <?php } ?>
            </label>
            <span >
              <?php
              $code = $attribute->getAttributeCode();
              switch ($attribute->getFrontendInput()) {
                case 'text':
                if(isset($_GET[$attribute->getAttributeCode()]) ||  (Mage::registry('current_oggetto') && $attribute->getIsForEdit()==2)) {
                  $oggy = Mage::registry('current_oggetto');
                  if(is_object($oggy)) {
                    $oggetto = Mage::getModel('score/oggetto')->load($oggy->getData($attribute->getAttributeCode()));
                    $val = $oggy->getData($attribute->getAttributeCode());
                  } elseif(isset($_GET[$attribute->getAttributeCode()])) {
                    $val = $_GET[$attribute->getAttributeCode()];
                    $oggetto = Mage::getModel('score/oggetto')->load($val);
                  }
                  echo "<h3>".((trim($oggetto->getName().' '.$oggetto->getTitle()))?$oggetto->getName().' '.$oggetto->getTitle():'none')."</h3>
                  <input type='hidden' name='{$attribute->getAttributeCode()}' value='{$val}' />";
                } else {
                  if (Mage::registry('current_oggetto')) {
                    $oggy = Mage::registry('current_oggetto');
                    $curValue = $oggy->getData($attribute->getAttributeCode());
                  } elseif (isset($_GET[$attribute->getAttributeCode()])) {
                    $curValue = $_GET[$attribute->getAttributeCode()];
                  };
                  if ($isRelated && !$isChain) {
                    $oggettos = Mage::getModel('score/oggetto')->getAvailableObjects($isRelated);
                      $data = array();
                    foreach ($oggettos as $object) {
                      $data[$object->getId()] =$object->getTitle().' '.$object->getName();
                    }
                    ?>
                    <select name="<?php echo $attribute->getAttributeCode() ?>"
                      id="<?php echo $attribute->getAttributeCode() ?>" style="width:100%"
                      class="nml  <?php echo $attribute->getFrontendClass() ?> <?php if ($attribute->getIsRequired()) { ?>  validate-select <?php } ?>"
                      >
                      <option value=""><?php echo Mage::helper('core')->__('Not Selected') ?></option>
                      <?php foreach ( $data as $key => $value) { ?>
                      <option value="<?php echo $key ?>" <?php if(isset($curValue) && ($key == $curValue || $value == $curValue)) { echo "selected"; } ?>><?php echo $value ?></option>
                      <?php } ?>
                    </select>
                    <script type="text/javascript">
                    jQuery(document).ready(function(){
                      jQuery('#<?php echo $attribute->getAttributeCode() ?>').select2({
                          allowClear: true,
                      });
                    });
</script>
<?php
} elseif($isDict) {
  $c = array();
  $elements = Mage::helper('score/oggetto')->getDictionaryValues($isDict);
  $data = array();
  foreach ($elements as $object) {
    $data[$object['id']] = $object['title'];
  }
  ?>
  <select name="<?php echo $attribute->getAttributeCode() ?>"
    id="<?php echo $attribute->getAttributeCode() ?>" style="width:100%"
    class="nml  <?php echo $attribute->getFrontendClass() ?> <?php if ($attribute->getIsRequired()) { ?>  validate-select <?php } ?>"
    >
    <?php foreach ( $data as $key => $value) { ?>
    <option value="<?php echo $key ?>" <?php if(isset($curValue) && ($key == $curValue || $value == $curValue)) { echo "selected"; } ?>><?php echo $value ?></option>
    <?php } ?>
  </select>
  <script type="text/javascript">
  jQuery(document).ready(function(){
      jQuery('#<?php echo $attribute->getAttributeCode() ?>').select2({
        allowClear: true,
      });
  });
  </script>
  <?php
} else {  ?>
<input name="<?php echo $attribute->getAttributeCode() ?>"
id="<?php echo $attribute->getAttributeCode() ?>" type="<?php if($hidden) { ?>hidden<?php } else { ?>text<?php } ?>" style="width:100%"
class="nml  <?php echo $attribute->getFrontendClass() ?> <?php if ($attribute->getIsRequired()) { ?>  required-entry <?php } ?>"
value="<?php if (Mage::registry('current_oggetto')) {
  $oggy = Mage::registry('current_oggetto');
  echo $oggy->getData($attribute->getAttributeCode());
} elseif (isset($_GET[$attribute->getAttributeCode()])) {
  echo $_GET[$attribute->getAttributeCode()];
} ?>" maxlength="255" />
<?php
}
}
break;
case 'price':
?>
<input name="<?php echo $attribute->getAttributeCode() ?>"
id="<?php echo $attribute->getAttributeCode() ?>" type="<?php if($hidden) { ?>hidden<?php } else { ?>text<?php } ?>" style="width:100%"
class="nml  <?php echo $attribute->getFrontendClass() ?> <?php if ($attribute->getIsRequired()) { ?>  required-entry <?php } ?>"
value="<?php if (Mage::registry('current_oggetto')) {
  $oggy = Mage::registry('current_oggetto');
  echo $oggy->getData($attribute->getAttributeCode());
} elseif (isset($_GET[$attribute->getAttributeCode()])) {
  echo $_GET[$attribute->getAttributeCode()];
} ?>" maxlength="255"  />
<?php
break;
case 'textarea':
?>
<textarea name="<?php echo $attribute->getAttributeCode() ?>"
  id="<?php echo $attribute->getAttributeCode() ?>" rows="10" style="width:100%"
  class="nml  <?php echo $attribute->getFrontendClass() ?> <?php if ($attribute->getIsRequired()) { ?>  required-entry <?php } ?>"><?php if ($oggy = Mage::registry('current_oggetto')) {
    echo $oggy->getData($attribute->getAttributeCode());
  } elseif (isset($_GET[$attribute->getAttributeCode()])) {
    echo $_GET[$attribute->getAttributeCode()];
  } ?></textarea>
  <?php if($attribute->getIsWysiwygEnabled()) { ?>
  <script type="text/javascript">
  <?php if(Mage::registry('slang')=='ru') { ?>
    var RLANG = {
      html: 'HTML',
      video: 'Добавить Видео...',
      image: 'Добавить Изображение...',
      table: 'Таблица',
      link: 'Ссылка',
      link_insert: 'Добавить Ссылку...',
      unlink: 'Убрать ссылку',
      formatting: 'Форматирование',
      paragraph: 'Параграф',
      quote: 'Цитата',
      code: 'Код',
      url: 'URL',
      header1: 'Заголовок 1',
      header2: 'Заголовок 2',
      header3: 'Заголовок 3',
      header4: 'Заголовок 4',
      bold:  'Жирный',
      italic: 'Курсив',
      fontcolor: 'Цвет шрифта',
      backcolor: 'Цвет фона',
      unorderedlist: 'Ненумированый список',
      orderedlist: 'Нумированый список',
      outdent: 'Outdent',
      indent: 'Indent',
      cancel: 'Отменить',
      insert: 'Вставить',
      save: 'Сохранить',
      _delete: 'Удалить',
      insert_table: 'Добавить таблицу...',
      insert_row_above: 'Добавить строку ниже',
      insert_row_below: 'Добавить строку выше',
      insert_column_left: 'Добавить колонку слева',
      insert_column_right: 'Добавить колонку справа',
      delete_column: 'Удалить колонку',
      delete_row: 'Удалить строку',
      delete_table: 'Удалить таблицу',
      rows: 'Строки',
      columns: 'Колонки',
      add_head: 'Добавить шапку',
      delete_head: 'Удалить шапку',
      title: 'Заголовок',
      image_position: 'Позиция',
      none: 'Нет',
      left: 'Слева',
      right: 'Справа',
      image_web_link: 'Ссылка',
      text: 'Текст',
      mailto: 'Email',
      web: 'URL',
      video_html_code: 'Код видео (Embed Code)',
      file: 'Добавить файл...',
      upload: 'Загрузить',
      download: 'Скачать',
      choose: 'Выбрать',
      or_choose: 'или выберите',
      drop_file_here: 'Перетяните файл сюда',
      align_left: 'Прижать влево',
      align_center: 'По центру',
      align_right: 'Прижать вправо',
      align_justify: 'Растянуть',
      horizontalrule: 'Вставить горизонтальную линию',
      fullscreen: 'На весь экран',
      deleted: 'Перечёркнутый',
      anchor: 'Якорь',
      widgets: 'Виджеты'
    };
    <?php } else { ?>
      var RLANG = {
        html: 'HTML',
        video: 'Insert Video...',
        image: 'Insert Image...',
        table: 'Table',
        link: 'Link',
        link_insert: 'Insert Link ...',
        unlink: 'Unlink',
        formatting: 'Formatting',
        paragraph: 'Paragraph',
        quote: 'Quote',
        code: 'Code',
        url: 'URL',
        header1: 'Header 1',
        header2: 'Header 2',
        header3: 'Header 3',
        header4: 'Header 4',
        bold:  'Bold',
        italic: 'Italic',
        fontcolor: 'Font Color',
        backcolor: 'Back Color',
        unorderedlist: 'Unordered List',
        orderedlist: 'Ordered List',
        outdent: 'Outdent',
        indent: 'Indent',
        cancel: 'Cancel',
        insert: 'Insert',
        save: 'Save',
        _delete: 'Delete',
        insert_table: 'Insert Table...',
        insert_row_above: 'Add Row Above',
        insert_row_below: 'Add Row Below',
        insert_column_left: 'Add Column Left',
        insert_column_right: 'Add Column Right',
        delete_column: 'Delete Column',
        delete_row: 'Delete Row',
        delete_table: 'Delete Table',
        rows: 'Rows',
        columns: 'Columns',
        add_head: 'Add Head',
        delete_head: 'Delete Head',
        title: 'Title',
        image_position: 'Position',
        none: 'None',
        left: 'Left',
        right: 'Right',
        image_web_link: 'Image Web Link',
        text: 'Text',
        mailto: 'Email',
        web: 'URL',
        video_html_code: 'Video Embed Code',
        file: 'Insert File...',
        upload: 'Upload',
        download: 'Download',
        choose: 'Choose',
        or_choose: 'Or choose',
        drop_file_here: 'Drop file here',
        align_left: 'Align Left',
        align_center: 'Align Center',
        align_right: 'Align Right',
        align_justify: 'Justify',
        horizontalrule: 'Insert Horizontal Rule',
        fullscreen: 'Fullscreen',
        deleted: 'Deleted',
        anchor: 'Anchor',
        widgets: 'Widgets'
      };
      <?php } ?>
      var widgets_list = '';
      </script>
      <link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl().'imperavi-redactor/css/style.css' ?>" />
      <link rel="stylesheet" href="<?php echo Mage::getBaseUrl().'imperavi-redactor/redactor/css/redactor.css' ?>" />
      <script src="<?php echo Mage::getBaseUrl().'imperavi-redactor/redactor/redactor-front.js' ?>"></script>
      <script type="text/javascript">
      jQuery('#<?php echo $attribute->getAttributeCode() ?>').redactor();
      </script>
      <?php } ?>
      <?php break;
      case 'date':
        $name = $attribute->getAttributeCode();
        $value = '';
        if ($oggy = Mage::registry('current_oggetto')) {
          $value = date('d/m/Y', strtotime($oggy->getData($attribute->getAttributeCode())));
        }
        echo Mage::app()->getLayout()->createBlock('core/html_date')
            ->setName($name)
            ->setId($attribute->getAttributeCode())
            ->setTitle($this->getAttributeLabel($attribute))
            ->setValue($value)
            ->setImage($this->getSkinUrl('images/calendar.gif'))
            ->setFormat('%d/%m/%y')
            ->setClass('input-text')
            ->getHtml();

      break;
       case 'media_image':
            ?>
            <input name="<?php echo $attribute->getAttributeCode() ?>"
            id="<?php echo $attribute->getAttributeCode() ?>" type="file"
            class="nml hidden <?php echo $attribute->getFrontendClass() ?> "
            value="<?php if (Mage::registry('current_oggetto')) {
              $oggy = Mage::registry('current_oggetto');
              echo $oggy->getData($attribute->getAttributeCode());
            } elseif (isset($_GET[$attribute->getAttributeCode()])) {
              echo $_GET[$attribute->getAttributeCode()];
            } ?>" maxlength="255"  />
            <button class="btn-large btn-danger" type="button" onclick="jQuery('#<?php echo $attribute->getAttributeCode() ?>').trigger('click')"><?php echo $this->__('Add Image'); ?></button>
            <?php
            break;
      case 'select':
      case 'boolean':
      case 'multiselect':
      $options = $attribute->getSource()->getAllOptions(false); ?>
      <select
      id="<?php echo $attribute->getAttributeCode() ?>" <?php if ($attribute->getFrontendInput() == 'multiselect') {
        echo 'multiple="true" size="5"';
      } ?>
      name="<?php echo $attribute->getAttributeCode() ?><?php if ($attribute->getFrontendInput() == 'multiselect') {
        echo '[]';
      } ?>" type="text" style="width:100%" class="nml <?php echo $attribute->getFrontendClass() ?> <?php if ($attribute->getIsRequired()) { ?>  validate-select <?php } ?>"
      value="" maxlength="255" >
      <?php if (count($options)) { ?>
      <?php foreach ($options as $key => $value) { ?>
      <option    <?php if (Mage::registry('current_oggetto') && in_array($value['value'], explode(',', Mage::registry('current_oggetto')->getData($attribute->getAttributeCode())))) {
        echo "selected='selected'";
      } ?> value="<?php echo $value['value'] ?>"><?php echo $value['label'] ?></option>
      <?php
    }
  } elseif (isset($customer) && is_object($customer)) {
    ?>
    <option <?php if (in_array(1, explode(',', $customer->getData($attribute->getAttributeCode())))) {
      echo "selected='selected'";
    } ?> value="1">Yes
  </option>
  <option <?php if (in_array(0, explode(',', $customer->getData($attribute->getAttributeCode())))) {
    echo "selected='selected'";
  } ?> value="0">No
</option>
<?php
} elseif ($isRelated && !$isChain) {
  $oggettos = Mage::getModel('score/oggetto')->getAvailableObjects($isRelated);
  foreach ($oggettos as $oggetto) {
    ?>
    <option <?php if (Mage::registry('current_oggetto') && in_array($oggetto->getId(), explode(',', Mage::registry('current_oggetto')->getData($code)))) {
      echo "selected='selected'";
    } ?>
    value="<?php echo $oggetto->getId() ?>"><?php echo $oggetto->getTitle() ?></option>
    <?php
  }
} ?>
</select>
<?php
break;
default:
break;
} ?>
</span>
</span>
<span class="col-md-5">
</span>
</li>
<?php if ($isChain && count($isChain) == 2) { ?>
<script type="text/javascript">
jQuery('#<?php echo $isChain[1] ?>').change(function () {
  update<?php echo $isChain[0] ?>();
});
      // jQuery(document).ready(function(){
        update<?php echo $isChain[0] ?>();
      //   });
function update<?php echo $isChain[0] ?>() {
  var updurl = '<?php echo Mage::getBaseUrl() ?>score/oggetto/getCollection';
  jQuery('#<?php echo $attribute->getAttributeCode() ?>').find('option').remove();
  isLoading('<?php echo $attribute->getAttributeCode() ?>', true);
  new Ajax.Request(updurl, {
    method: 'post',
    action_content: '',
    parameters: {easy_ajax: 1, attribute_set_id: <?php echo $isChain[0] ?>,
      <?php echo $isChain[1] ?>:
      $('<?php echo $isChain[1] ?>').value
    }
    ,
    onComplete: function (transport) {
      isLoading('<?php echo $attribute->getAttributeCode() ?>', false);
      var data = transport.responseText.evalJSON();
      for (i = 0; i < data.collection.length; i++) {
        var option = new Option;
        option.value = data.collection[i].id;
        option.label = data.collection[i].title;
        <?php if(is_object(Mage::registry('current_oggetto'))) { ?>
          if ('<?php echo Mage::registry('current_oggetto')->getData($code) ?>'.indexOf(data.collection[i].id) != -1) {
            option.selected = "selected";
          }
          <?php } ?>
          $('<?php echo $attribute->getAttributeCode() ?>').appendChild(option);
        }
      }
    })
  ;
}
</script>
<?php } ?>
<?php if ($isUser) {
  $users = Mage::helper('score/oggetto')->getUsersCollection();
  foreach ($users as $user) {
    $c[] = "{id: '{$user->getId()}', text: '{$user->getName()}'}";
  }
  $data = '[' . implode(',', $c) . ']';
  ?>
  <script type="text/javascript">
      //jQuery(document).ready(function(){
        jQuery('#<?php echo $attribute->getAttributeCode() ?>').select2({
          data: <?php echo $data ?>,
          multiple: true,
          allowClear: false
        });
      // });
</script>
<?php } ?>
<?php } ?>
<?php if ($this->getCanBePrivate()) { ?>
<li class="last row-fluid">
  <span class="col-md-11">
    <label class="desc inline mright20">Is Public <span class="req">*</span>
      <a rel="popover" data-content="Public <?php echo $this->getSet() ?> is available for everybody in the web. Non-public can be viewed only by you.
        <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
        <a href='<?php echo Mage::getBaseUrl() ?>customer/account/login'>Login or register</a> today to be able create Private <?php echo $this->getSet() ?>s.
        <?php } ?>" class="ico-fb ehut-icon-social btn btn-success disabled" href="#" data-original-title="How it works?">?</a>
      </label>
      <div class="inline mright20">
        Yes <input type="radio" name="is_public[]"
        value="1" <?php if (!Mage::getSingleton('customer/session')->isLoggedIn() || (Mage::registry('current_oggetto') && Mage::registry('current_oggetto')->getData('is_public') == 1)) { ?> checked="checked" <?php } ?>
        onchange="isPublic(1)"/>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <?php if (Mage::getSingleton('customer/session')->isLoggedIn()) { ?> <input type="radio" name="is_public[]"
        value="0" <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) { ?> disabled class="" <?php } else if ((Mage::registry('current_oggetto') && Mage::registry('current_oggetto')->getData('is_public') != 1) || (!Mage::registry('current_oggetto') && Mage::getSingleton('customer/session')->isLoggedIn())) { ?> checked="checked" <?php } ?>
        onchange="isPublic(0)"/> <?php } else { ?>
        <?php
        $_social = $this->getLayout()->createBlock('ehut_sociallogin/button');
        echo $_social->setTemplate('ehut_sociallogin/button_short.phtml')->toHtml();
        ?>
        <?php } ?>
        No (for registered users only)
      </div>
    </span>
  </li>
  <?php } ?>
  <li class="row-fluid" style="margin-top:10px;">
    <span class="col-md-11">
        <button class="btn-large btn-danger pull-right" type="submit" title="<?php echo $this->__('Save') ?>"><?php echo $this->__('Save') ?></button>
      </span>
    </li>
  </ul>
</form>
</div>
<script type="text/javascript">
var form = new VarienForm('createForm');
function isPublic(show) {
}
</script>
<?php /* <script type="text/javascript">
jQuery(document).ready(function($) {
jQuery('#review_rating-block').raty({
cancel: false,
half: true,
<?php if(Mage::registry('current_oggetto')) { $oggetto = Mage::registry('current_oggetto'); ?> score: <?php echo $oggetto->getData('review_rating') ?>, <?php } ?>
starType : 'i',
targetScore: '#review_rating',
});
});
</script> */ ?>
