<script type="text/javascript" src="<?php echo $this->helper('core/js')->getJsUrl('mage/adminhtml/grid_front.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->helper('core/js')->getJsUrl('mage/adminhtml/hash_front.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->helper('core/js')->getJsUrl('mage/adminhtml/events.js') ?>"></script>

<?php $numColumns = sizeof($this->getColumns());
if($this->getCollection()): ?>
    <?php if($this->canDisplayContainer()): ?>
    <?php if($this->getGridHeader()): ?>
        <div class="content-header">
            <table cellspacing="0">
                <tr>
                    <td style="width:50%;"><h3><?php echo $this->getTitle() ?></h3></td>
                    <td style="width:50%;"><?php echo $this->getChildHtml('add') ?></td>
                </tr>
            </table>
        </div>
    <?php endif ?>

    <div id="<?php echo $this->getId() ?>" class="row-fluid">


        <?php endif; ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php if($this->getPagerVisibility() || $this->getExportTypes() || $this->getFilterVisibility()): ?>
            <table cellspacing="0" class="actions col-md-8">
                <tr class="filter dt h50">
                    <?php if($this->getPagerVisibility()): ?>
                        <th class="dtc pull-left">
                            <?php echo $this->__('Page') ?>

                            <?php $_curPage  = $this->getCollection()->getCurPage() ?>
                            <?php $_lastPage = $this->getCollection()->getLastPageNumber() ?>
                            <?php if($_curPage>1): ?>
                                <a href="#" title="<?php echo $this->__('Previous page') ?>" onclick="<?php echo $this->getId() ?>JsObject.setPage('<?php echo ($_curPage-1) ?>');return false;"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_left.gif') ?>" alt="Go to Previous page" class="arrow"/></a>
                            <?php else: ?>
                                <img src="<?php echo $this->getSkinUrl('images/pager_arrow_left_off.gif') ?>" alt="Go to Previous page" class="arrow"/>
                            <?php endif; ?>

                            <input type="text" name="<?php echo $this->getVarNamePage() ?>" value="<?php echo $_curPage ?>" class="input-text nm w50" onkeypress="<?php echo $this->getId() ?>JsObject.inputPage(event, '<?php echo $_lastPage ?>')"/>

                            <?php if($_curPage < $_lastPage): ?>
                                <a href="#" title="<?php echo $this->__('Next page') ?>" onclick="<?php echo $this->getId() ?>JsObject.setPage('<?php echo ($_curPage+1) ?>');return false;"><img src="<?php echo $this->getSkinUrl('images/pager_arrow_right.gif') ?>" alt="Go to Next page" class="arrow"/></a>
                            <?php else: ?>
                                <img src="<?php echo $this->getSkinUrl('images/pager_arrow_right_off.gif') ?>" alt="Go to Previous page" class="arrow"/>
                            <?php endif; ?>

                            <?php echo $this->__('of %s pages', $this->getCollection()->getLastPageNumber()) ?>
                            <span class="separator mleft10 mright10">|</span>
                            <?php echo $this->__('View') ?>
                            <select class="w50 nm" name="<?php echo $this->getVarNameLimit() ?>" onchange="<?php echo $this->getId() ?>JsObject.loadByElement(this)">
                                <option value="20"<?php if($this->getCollection()->getPageSize()==20): ?> selected="selected"<?php endif; ?>>20</option>
                                <option value="30"<?php if($this->getCollection()->getPageSize()==30): ?> selected="selected"<?php endif; ?>>30</option>
                                <option value="50"<?php if($this->getCollection()->getPageSize()==50): ?> selected="selected"<?php endif; ?>>50</option>
                                <option value="100"<?php if($this->getCollection()->getPageSize()==100): ?> selected="selected"<?php endif; ?>>100</option>
                                <option value="200"<?php if($this->getCollection()->getPageSize()==200): ?> selected="selected"<?php endif; ?>>200</option>
                            </select>
                            <?php echo $this->__('per page') ?><span class="separator mleft10 mright10">|</span>
                            <?php echo $this->__('Total %d records found', $this->getCollection()->getSize()) ?>
                            <span id="<?php echo $this->getHtmlId() ?>-total-count" class="no-display"><?php echo $this->getCollection()->getSize() ?></span>
                            <?php if($this->getRssLists()): ?>
                                <?php foreach ($this->getRssLists() as $_rss): ?>
                                    <span class="separator  mleft10 mright10">|</span><a href="<?php echo $_rss->getUrl() ?>" class="link-feed"><?php echo $_rss->getLabel() ?></a>
                                <?php endforeach ?>
                            <?php endif; ?>
                        </th>
                    <?php endif ?>

                </tr>
            </table>
        <?php endif; ?>
        <div class="buttons-set mtop20 pull-right col-md-4">
            <?php echo $this->getMainButtonsHtml() ?>
            <?php        if($this->getAdd())  { ?>
            <button id=""  href="<?php  echo $this->getAddUrl()  ?>" title="Add" type="button" class="scalable task button-add"><span><span><span><?php echo $this->getAddTitle() ?></span></span></span></button>
            <?php } ?>
        </div>

        <div class="grid col-md-12 nml">
            <div class="hor-scroll">
                <table cellspacing="0" class="data" id="<?php echo $this->getId() ?>_table">
                    <?php foreach ($this->getColumns() as $_column): ?>
                        <col <?php echo $_column->getHtmlProperty() ?> />
                        <?php if ($_column->getEditable() && !$_column->getEditOnly()) : ?>
                            <col <?php echo $_column->getHtmlProperty() ?> />
                        <?php endif ?>
                    <?php endforeach; ?>
                    <?php if ($this->getHeadersVisibility() || $this->getFilterVisibility()): ?>
                        <thead>
                        <?php if ($this->getHeadersVisibility()): ?>
                            <tr class="headings">
                                <?php foreach ($this->getColumns() as $_column): ?>
                                    <th<?php echo $_column->getHeaderHtmlProperty() ?>>
                            <span class="nobr">
                                <?php echo $_column->getHeaderHtml() ?>
                            </span>
                                    </th>
                                <?php endforeach; ?>
                            </tr>
                        <?php endif; ?>
                        <?php if ($this->getFilterVisibility()): ?>
                            <tr class="filter">
                                <?php $i=0;foreach ($this->getColumns() as $_column): ?>
                                    <th<?php echo $_column->getHeaderHtmlProperty() ?>>
                                        <div class="inline w100">
                                        <?php echo $_column->getFilterHtml() ?>
                                        </div>
                                        <?php /*if(substr_count($_column->getHeaderHtmlProperty(),'no-link')==0) { ?>
                                            <button class="icon icon-search inline f15 black small-search-button pull-left mleft10" name="search" onclick="<?php echo $this->getJsObjectName() ?>.doFilter()">
                                            </button>
                                        <?php } */ ?>
                                    </th>
                                <?php endforeach; ?>
                            </tr>
                        <?php endif ?>
                        </thead>
                    <?php endif; ?>
                    <?php if ($this->getCountTotals()): ?>
                        <tfoot>
                        <tr class="totals">
                            <?php foreach ($this->getColumns() as $_column): ?>
                                <th class="<?php echo $_column->getCssProperty() ?>"><?php echo ($_column->hasTotalsLabel()) ? $_column->getTotalsLabel() : $_column->getRowField($_column->getGrid()->getTotals()) ?>&nbsp;</th>
                            <?php endforeach; ?>
                        </tr>
                        </tfoot>
                    <?php endif; ?>

                    <tbody>
                    <?php if (($this->getCollection()->getSize()>0) && (!$this->getIsCollapsed())): ?>
                        <?php foreach ($this->getCollection() as $_index=>$_item): ?>
                            <tr title="<?php echo $this->getRowUrl($_item) ?>"<?php if ($_class = $this->getRowClass($_item)):?> class="<?php echo $_class; ?>"<?php endif;?> >
                                <?php $i=0;foreach ($this->getColumns() as $_column): ?>

                                    <?php if ($this->shouldRenderCell($_item, $_column)):?>
                                        <?php $_rowspan = $this->getRowspan($_item, $_column);?>
                                        <td <?php echo ($_rowspan ? 'rowspan="' . $_rowspan . '" ' : '') ?>class="<?php echo $_column->getCssProperty() ?> <?php echo ++$i==$numColumns?'last':'' ?>">
                                            <?php echo (($_html = $_column->getRowField($_item)) != '' ? htmlspecialchars_decode($_html) : '&nbsp;') ?>
                                        </td>
                                        <?php if ($this->shouldRenderEmptyCell($_item, $_column)):?>
                                            <td colspan="<?php echo $this->getEmptyCellColspan($_item)?>" class="last"><?php echo $this->getEmptyCellLabel()?></td>
                                        <?php endif;?>
                                    <?php endif;?>

                                <?php endforeach; ?>
                            </tr>
                            <?php if ($_multipleRows = $this->getMultipleRows($_item)):?>
                                <?php foreach ($_multipleRows as $_i):?>
                                    <tr>
                                        <?php $i=0;foreach ($this->getMultipleRowColumns($_i) as $_column): ?>
                                            <td class="<?php echo $_column->getCssProperty() ?> <?php echo ++$i==$numColumns-1?'last':'' ?>">
                                                <?php echo (($_html = $_column->getRowField($_i)) != '' ? $_html : '&nbsp;') ?>
                                            </td>
                                        <?php endforeach; ?>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>

                            <?php if ($this->shouldRenderSubTotal($_item)): ?>
                                <tr class="subtotals">
                                    <?php $i = 0; foreach ($this->getSubTotalColumns() as $_column): ?>
                                        <td class="<?php echo $_column->getCssProperty() ?> <?php echo ++$i == $numColumns ? 'last' : '' ?>">
                                            <?php echo ($_column->hasSubtotalsLabel() ? $_column->getSubtotalsLabel() :
                                                $_column->getRowField($this->getSubTotalItem($_item))
                                            );
                                            ?>
                                        </td>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    <?php elseif ($this->getEmptyText()): ?>
                        <tr>
                            <td class="empty-text <?php echo $this->getEmptyTextClass() ?>" colspan="100"><?php echo $this->getEmptyText() ?></td>
                        </tr>
                    <?php endif; ?>
                    </tbody>
                </table>

            </div>
        </div>
        <?php if($this->canDisplayContainer()): ?>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var <?php echo $this->getJsObjectName() ?> = new varienGrid('<?php echo $this->getId() ?>', '<?php echo $this->getGridUrl() ?>', '<?php echo $this->getVarNamePage() ?>', '<?php echo $this->getVarNameSort() ?>', '<?php echo $this->getVarNameDir() ?>', '<?php echo $this->getVarNameFilter() ?>');
        <?php echo $this->getJsObjectName() ?>.useAjax = '<?php echo $this->getUseAjax() ?>';
        <?php if($this->getRowClickCallback()): ?>
        <?php echo $this->getJsObjectName() ?>.rowClickCallback = <?php echo $this->getRowClickCallback() ?>;
        <?php endif; ?>
        <?php /* if($this->getCheckboxCheckCallback()): ?>
            <?php echo $this->getJsObjectName() ?>.checkboxCheckCallback = <?php echo $this->getCheckboxCheckCallback() ?>;
        <?php endif; */ ?>
        <?php if($this->getRowInitCallback()): ?>
        <?php echo $this->getJsObjectName() ?>.initRowCallback = <?php echo $this->getRowInitCallback() ?>;
        <?php echo $this->getJsObjectName() ?>.initGridRows();
        <?php endif; ?>
        Event.observe(window,'load',function() {
            <?php echo $this->getJsObjectName() ?>.resetFilter();
        });
        //]]>
    </script>
<?php endif; ?>
<?php endif ?>
<?php echo $this->getChildHtml('serializer') ?>
