<?php
$check_show_social = Mage::helper('ehut_sociallogin')->checkShowSociallogin();
if($check_show_social == true && Mage::getSingleton('customer/session')->IsLoggedIn() == false):
?>
    <link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->getSkinUrl('ehut_sociallogin/css/style.css');?>"/>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('ehut_sociallogin/js/sociallogin.js');?>"></script>
    <div class="ehut-socialconnect-social " style="text-align: center">
        <div class="account-login">
                        <div class="ehut-social-button-login">
                            <?php
                             if($this->getButtons()){
                                foreach($this->getButtons() as $button){
                                    echo $button->render();
                                }
                             }
                            ?>
                        </div>
        </div>


    </div>
    <?php
    if(Mage::getSingleton('core/design_package')->getTheme('frontend') == 'iphone') { ?>
    <style type="text/css">
        .ehut-social-button-login .ehut-icon-social{
            float: left;
        }
    </style>
    <?php } ?>
<?php else: ?> 
 <ul class="links nav pull-right mright20">
        <li class="dropdown">
            <a class="dropdown-toggle np mtop5" style="height: 35px" href="<?php echo Mage::getBaseUrl().Mage::registry('slang')  ?>/customer/account">
                <?php            $customerId                    = Mage::helper('customer')->getCustomer()->getId();
                $customerMagemlm        = Mage::getModel('magemlm/customer')->load($customerId, 'customer_id'); ?>
                <?php if ($customerMagemlm->getMagemlmImage()) { ?>
                    <img src="<?php echo  Mage::helper('catalog/image')->resizeImg(Mage::getBaseDir('media') . DS . 'magemlm' ,$customerMagemlm->getMagemlmImage(),35); ?>" />
                <?php } else { ?>
                    <img src="<?php echo Mage::helper('catalog/image')->resizeImg(Mage::getBaseDir().'/'.str_replace(Mage::getBaseUrl(),'',$this->getSkinUrl('images/')),'def_user.jpeg',35) ?>" />
                <?php  } ?>

            </a>
        </li>
    </ul>

<?php endif;?>
