<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="col-md-4 col-md-offset-4 col-xs-12">
<div class="well ">
<div class="page-title ">
    <h3><?php echo $this->__('Forgot Your Password?') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" class="form-horizontal centered p10">
    <fieldset class="">
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <div class="">
                <label for="email_address" class="inline"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="inline mleft20">
	                <div class="input-prepend">
	                	<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                    </div>

                </div>

        </div>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <p class="help-block"><?php echo $this->__('* Required Fields') ?></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-success"><span><span><?php echo $this->__('Submit') ?></span></span></button>
	        <div class="back-link centered">
                <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Back to Login') ?></a>
            </div>
        </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
</div></div>