
<?php
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$block = new EH_SocialLogin_Block_Button();
if (Mage::getStoreConfig('ehut_sociallogin/general/showonloginpage') == 'inloginbox') {
    $pos = strpos($currentUrl,'customer/account/login');
    if($pos !== false) {
        if ($this->checkEnable() == true):?>
            <a onclick="showEhutSocialPopup('<?php echo $this->_getButtonUrl(); ?>', <?php echo $this->getWidth(); ?>, <?php echo $this->getHeight(); ?>);">
                <div class="<?php echo $this->getClass(); ?> ehut-icon-social"
                     title="<?php echo $this->__('Connect with ') . $this->__($this->getTitle()); ?>"></div>
            </a>
        <?php endif;
    } else {
        if ($this->checkEnable() == true):
                if($this->getClass()=='fa-vk') { 
?>
             <a href="https://oauth.vk.com/authorize?v=5.31&client_id=5079985&redirect_uri=<?php echo Mage::getBaseUrl() ?>ehut_sociallogin/vk/connect/&scope=email,status&fields=first_name,last_name,bdate,status,city,country">
                <image src="<?php echo $this->getSkinUrl('ehut_sociallogin/images/vkontakte_icon.png') ?>" />
            </a>

        <?php
                } else { 
            ?>
            <button type="button" class=" ehut-icon-social noborder nobg mbottom10"
                    title="<?php echo $this->__('Connect with ') . $this->__($this->getTitle()); ?>"
                    onclick="showEhutSocialPopup('<?php echo $this->_getButtonUrl(); ?>', <?php echo $this->getWidth(); ?>, <?php echo $this->getHeight(); ?>);">
<image src="<?php echo $this->getSkinUrl('ehut_sociallogin/images/<?php echo $this->getName(); ?>_icon.png') ?>" />
                </button>
        <?php 
                }
                endif;
    }

} else {
    if ($this->checkEnable() == true):
          if($this->getClass()=='fa-vk') { 
?>
         <button type="button" class="ehut-icon-social noborder nobg  " onclick="document.location.href = 'https://oauth.vk.com/authorize?v=5.31&client_id=5079985&redirect_uri=<?php echo Mage::getBaseUrl() ?>ehut_sociallogin/vk/connect/&scope=email,status&fields=first_name,last_name,bdate,status,city,country'">
            <image src="<?php echo $this->getSkinUrl('ehut_sociallogin/images/vkontakte_icon.png') ?>" />
        </button>

        <?php
                } else { 
            ?>
        <button type="button" class="ehut-icon-social noborder nobg mbottom10 "
                title="<?php echo $this->__('Connect with ') . $this->__($this->getTitle()); ?>"
                onclick="showEhutSocialPopup('<?php echo $this->_getButtonUrl(); ?>', <?php echo $this->getWidth(); ?>, <?php echo $this->getHeight(); ?>);">
            <image src="<?php echo $this->getSkinUrl('ehut_sociallogin/images/'.$this->getName().'_icon.png') ?>" />

</button>
    <?php 
            } 
            endif;
}
?>

