<p class="switcher"><label for="order_switcher"><?php echo $this->__('Choose Order') ?>:</label>
    <select name="order_switcher" id="order_switcher" onchange="return switchOrder(this);">
        <option value="">&lt;Empty&gt;</option>
        <?php foreach ($this->getOrders() as $order): ?>
            <option value="<?php echo $order->getIncrementId() ?>"<?php if($this->getOrderId() == $order->getIncrementId()): ?> selected="selected"<?php endif; ?>><?php echo $order->getIncrementId() ?></option>
        <?php endforeach; ?>
    </select>
</p>
<script type="text/javascript">
    function switchOrder(obj){

        var storeParam = obj.value ? 'order/'+obj.value + '/' : '';
        if(obj.switchParams){
            storeParam+= obj.switchParams;
        }
        <?php if($this->getUseConfirm()): ?>
            if(confirm("<?php echo $this->__('Please confirm site switching. All data that hasn\'t been saved will be lost.') ?>")){
                setLocation('<?php echo $this->getSwitchUrl() ?>'+storeParam);
                return true;
            }
            else {
                obj.value = '<?php echo $this->getStoreId() ?>';
            }
            return false;
            <?php else: ?>
            setLocation('<?php echo $this->getSwitchUrl() ?>'+storeParam);
            <?php endif; ?>
    }
</script>