<?php 
	$magemlmLevels 	= Mage::getModel('magemlm/unilevel') -> getCollection();
	$editUrl 			= Mage::helper("adminhtml") -> getUrl("*/*/edit");
	$deleteUrl 			= Mage::helper("adminhtml") -> getUrl("*/*/delete");
	$sum				= Mage::helper('magemlm')->compensationSum() ; 
?>

<div class="content-header">
    <h3 class="icon-head head-sales-order"><?php echo $this -> __('Commissions levels'); ?><i> (<?php echo $this->__('sum'); ?> = <?php echo $sum ?>%)</i></h3>
    <p class="magemlm-buttons">
    	<button style="" class="scalable add" type="button" title="Save Account" id="id_5e2f7c269e1d3bbc886158b7d0906c2b" onClick="window.location = '<?php echo $editUrl; ?>'">
    		<span><?php echo $this->__('Add commission level') ?></span>
    	</button>
  	</p>
</div>


<?php $i = 0;?>
<?php foreach ($magemlmLevels as $magemlmLevel) : ?>
	<?php if ($i >= 1) : ?>
			<div style="background-image: url('<?php echo $this->getSkinUrl('images/admin_magemlm_arrow.png'); ?>'); margin-left: <?php echo (($i-1) * 95); ?>px; width: 95px; heighT: 80px; float: left; margin-top: -15px;"></div>
	<?php endif ; ?>
	<div style="clear: right; width: 600px; height: 95px; margin-left: <?php echo ($i * 95); $i++ ?>px;">
		<button class="magemlm-admin-edit" 		onClick="window.location = '<?php echo $editUrl; ?>id/<?php echo $magemlmLevel->getId()?>/'";></button>
		<button class="magemlm-admin-delete"  	onClick="window.location = '<?php echo $deleteUrl; ?>id/<?php echo $magemlmLevel->getId()?>/'";></button>
		
		<div  class="entry-edit" style="width: 396px; float: left;">
			<div class="entry-edit-head">
				<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this -> __('Level name: ') . $magemlmLevel -> getLevelName(); ?></h4>
			</div>
			<div class="fieldset" style="height: 32px; padding-top: 14px;">
				<p class="magemlm-level"><?php echo $this->__('Value: ') ?> <?php echo $magemlmLevel -> getLevelCommission(); ?>%</p>
			</div>
		</div>
	</div>
<?php endforeach ; ?>
