<div class="account-login">

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" autocomplete="off">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <input style="display:none">
        <input type="password" style="display:none">
        <!-- Fool chrome -->
        <div class="centered">
            <div class="new-users">
                <div class="content ">
                    <?php
                    $_social = $this->getLayout()->createBlock('ehut_sociallogin/button');
                    echo $_social->setTemplate('ehut_sociallogin/button.phtml')->toHtml();
                    ?>

                    <div class="buttons-set">
                        <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="btn-danger btn" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
                    </div>

                    <h3><?php echo $this->__('If you have an account with us, please log in.') ?></h3>
                    <ul class="form-list nml mtop10">
                        <li>
                            <div class="input-box">
                                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry" autocomplete="0" placeholder="<?php echo Mage::helper('core')->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <input autocomplete="off" type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" placeholder="<?php echo $this->__('Password') ?>" />
                            <br/>
                                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f10 f-left"><?php echo $this->__('Forgot Your Password?') ?></a>

                            </div>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

                    <div class="col-2 registered-users">
                        <div class="buttons-set">
                            <button type="submit" class="btn-danger btn" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('LogIn') ?></span></span></button>

                        </div>
                    </div>
                </div>

            </div>
        </div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>
