<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php /* @var $this Mage_Score_Block_Oggetto_View_Abstract */?>
<?php $_oggetto = $this->getOggetto() ?>

<?php if ($_oggetto->isAvailable()): ?>
    <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span class="label"><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span class="label label-important"><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>
<?php echo $this->getChildHtml('oggetto_type_data_extra') ?>
<?php echo $this->getPriceHtml($_oggetto) ?>
